//membuat data data film
import {Film} from './app/shared/models/Film'

export const sample_film: Film[]= [
    {
        id:'1',
        name: 'Rocky Balboa 4K Blu-ray',
        minutes: '102 min',
        price: 420000,
        favorite: false,
        studio: 'Warner Bros',
        stars: 4.5,
        imageUrl: 'assets/film1.jpg',
        tags: ['Action', 'Sport', 'Drama'],
      },
      {
        id:'2',
        name: 'Vikings: The Complete Series Blu-ray',
        minutes: '3786 min',
        price: 1200000,
        favorite: true,
        studio: 'Warner Bros',
        stars: 4.7,
        imageUrl: 'assets/film2.jpg',
        tags: ['Action', 'Drama'],
      },
      {
        id:'3',
        name: 'La Femme Nikita 4K Blu-ray',
        minutes: '117 min',
        price: 430000,
        favorite: false,
        studio: 'Sony Pictures',
        stars: 3.5,
        imageUrl: 'assets/film3.jpg',
        tags: ['Drama', 'Thriller'],
      },
      {
        id:'4',
        name: 'Ghostbusters: Frozen Empire 4K Blu-ray',
        minutes: '115 min',
        price: 350000,
        favorite: true,
        studio: 'Sony Pictures',
        stars: 3.3,
        imageUrl: 'assets/film4.jpg',
        tags: ['Fantasy', 'Sci-Fi'],
      },
      {
        id:'5',
        name: 'Dune: Part Two (4K Ultra HD + Digital) [4K UHD]',
        minutes: '166 min',
        price: 410000,
        favorite: false,
        studio: 'Warner Bros',
        stars: 3.0,
        imageUrl: 'assets/film5.jpg',
        tags: ['Sci-Fi', 'Action'],
      },
      {
        id:'6',
        name: 'Mr. Robot: The Complete Series Blu-ray',
        minutes: '2227 min',
        price: 920000,
        favorite: false,
        studio: 'Universal Studio',
        stars: 4.0,
        imageUrl: 'assets/film6.jpg',
        tags: ['Thriller', 'Crime'],
      },
      {
        id:'7',
        name: 'American Sniper 4K Blu-ray',
        minutes: '133 min',
        price: 300000,
        favorite: false,
        studio: 'Warner Bros',
        stars: 4.0,
        imageUrl: 'assets/film7.jpg',
        tags: ['Action', 'History'],
      },
      {
        id:'8',
        name: 'Friends: The Complete Series Blu-ray',
        minutes: '4800 min',
        price: 530000,
        favorite: false,
        studio: 'Warner Bros',
        stars: 4.8,
        imageUrl: 'assets/film8.jpg',
        tags: ['Comedy', 'Romance'],
      },
      {
        id:'9',
        name: 'The Flash: The Complete Series Blu-ray',
        minutes: '11040 min',
        price: 730000,
        favorite: false,
        studio: 'Warner Bros',
        stars: 4.5,
        imageUrl: 'assets/film9.jpg',
        tags: ['Action', 'Sci-Fi'],
      },
      {
        id:'10',
        name: 'Oceans Trilogy 4K Blu-ray',
        minutes: '11040 min',
        price: 370000,
        favorite: false,
        studio: 'Warner Bros',
        stars: 3.8,
        imageUrl: 'assets/film10.jpg',
        tags: ['Crime', 'Comedy'],
      },
      
      
]